const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Sprite,
		C3.Behaviors.Physics,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Behaviors.solid,
		C3.Plugins.Keyboard,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.MoveTo,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Spritefont2.Acts.TypewriterText,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.SetFullscreenQuality,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Acts.AddRemoveAnimation,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Cnds.EveryTick,
		C3.ScriptsInEvents.Fase1pronto_Event18_Act1,
		C3.Plugins.Text.Acts.SetText
	];
};
self.C3_JsPropNameTable = [
	{CidadeFundo: 0},
	{Esmaecer: 0},
	{Legendahistoria: 0},
	{fundostart: 0},
	{Nomeprincipal: 0},
	{historia: 0},
	{Mouse: 0},
	{jogar: 0},
	{zumbivida: 0},
	{fundofase1: 0},
	{Física: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{personagem: 0},
	{Sólido: 0},
	{chaofase1: 0},
	{Teclado: 0},
	{Variável1: 0},
	{zumbi: 0},
	{Projétil: 0},
	{DestruirForaDoLayout: 0},
	{MoverPara: 0},
	{bala: 0},
	{Áudio: 0},
	{moeda: 0},
	{PlanoDeFundoEmBlocos2: 0},
	{PlanoDeFundoEmBlocos4: 0},
	{PlanoDeFundoEmBlocos5: 0},
	{Âncora: 0},
	{cmoeda: 0},
	{numeromoeda: 0},
	{boss: 0},
	{Sprite: 0},
	{explosion: 0},
	{parabens: 0},
	{menu: 0},
	{vocePerdeu: 0},
	{irtelainicial: 0},
	{textv: 0},
	{vidap: 0},
	{zvida: 0},
	{ultmoeda: 0},
	{bvida: 0}
];

self.InstanceType = {
	CidadeFundo: class extends self.ITiledBackgroundInstance {},
	Legendahistoria: class extends self.ISpriteFontInstance {},
	fundostart: class extends self.ITiledBackgroundInstance {},
	Nomeprincipal: class extends self.ISpriteFontInstance {},
	historia: class extends self.ISpriteFontInstance {},
	Mouse: class extends self.IInstance {},
	jogar: class extends self.ISpriteFontInstance {},
	fundofase1: class extends self.ITiledBackgroundInstance {},
	personagem: class extends self.ISpriteInstance {},
	chaofase1: class extends self.ITiledBackgroundInstance {},
	Teclado: class extends self.IInstance {},
	zumbi: class extends self.ISpriteInstance {},
	bala: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	moeda: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos2: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos4: class extends self.ITiledBackgroundInstance {},
	PlanoDeFundoEmBlocos5: class extends self.ITiledBackgroundInstance {},
	cmoeda: class extends self.ITextInstance {},
	numeromoeda: class extends self.ITextInstance {},
	boss: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	explosion: class extends self.ISpriteInstance {},
	parabens: class extends self.ISpriteFontInstance {},
	menu: class extends self.ISpriteFontInstance {},
	vocePerdeu: class extends self.ISpriteFontInstance {},
	irtelainicial: class extends self.ISpriteFontInstance {},
	textv: class extends self.ITextInstance {},
	vidap: class extends self.ITextInstance {}
}